# Generated by Django 4.2.3 on 2023-07-10 03:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="ToDo",
        ),
    ]
